<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePersonTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password', 60);
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('users');
    }

    /*Public function setupValues(){
        INSERT INTO `subscription_status` (`subscription_status_id`, `name`) VALUES ( 'trial'), ( 'full');
        INSERT INTO `condat_v5`.`standard_subscriptions` (`standard_subscription_id`, `name`, `description`, `amount`) VALUES (NULL, 'basic', 'Basic system will handle client and their invoice details', '500');
        INSERT INTO `user_levels` (`user_level_id`, `name`, `description`, `value`) VALUES
        ('agency_admin', 'administrator of that agency', 12),
        ( 'agency_staff', 'staff members of agency', 9),
        ( 'agency_accountant', 'accountant of agency', 3),
        ( 'admin', 'adminstrator of all system', 15),
        ( 'super_admin', 'main admin who manages everything', 18);
            INSERT INTO `countries` (`code`, `name`) VALUES
            ('AD', 'Andorra'),
            ('AE', 'United Arab Emirates'),
            ('AF', 'Afghanistan'),
            ('AG', 'Antigua and Barbuda'),
            ('AI', 'Anguilla'),
            ('AL', 'Albania'),
            ('AM', 'Armenia'),
            ('AO', 'Angola'),
            ('AQ', 'Antarctica'),
            ('AR', 'Argentina'),
            ('AS', 'American Samoa'),
            ('AT', 'Austria'),
            ('AU', 'Australia'),
            ('AW', 'Aruba'),
            ('AX', 'Åland'),
            ('AZ', 'Azerbaijan'),
            ('BA', 'Bosnia and Herzegovina'),
            ('BB', 'Barbados'),
            ('BD', 'Bangladesh'),
            ('BE', 'Belgium'),
            ('BF', 'Burkina Faso'),
            ('BG', 'Bulgaria'),
            ('BH', 'Bahrain'),
            ('BI', 'Burundi'),
            ('BJ', 'Benin'),
            ('BL', 'Saint Barthélemy'),
            ('BM', 'Bermuda'),
            ('BN', 'Brunei'),
            ('BO', 'Bolivia'),
            ('BQ', 'Bonaire'),
            ('BR', 'Brazil'),
            ('BS', 'Bahamas'),
            ('BT', 'Bhutan'),
            ('BV', 'Bouvet Island'),
            ('BW', 'Botswana'),
            ('BY', 'Belarus'),
            ('BZ', 'Belize'),
            ('CA', 'Canada'),
            ('CC', 'Cocos [Keeling] Islands'),
            ('CD', 'Democratic Republic of the Congo'),
            ('CF', 'Central African Republic'),
            ('CG', 'Republic of the Congo'),
            ('CH', 'Switzerland'),
            ('CI', 'Ivory Coast'),
            ('CK', 'Cook Islands'),
            ('CL', 'Chile'),
            ('CM', 'Cameroon'),
            ('CN', 'China'),
            ('CO', 'Colombia'),
            ('CR', 'Costa Rica'),
            ('CU', 'Cuba'),
            ('CV', 'Cape Verde'),
            ('CW', 'Curacao'),
            ('CX', 'Christmas Island'),
            ('CY', 'Cyprus'),
            ('CZ', 'Czech Republic'),
            ('DE', 'Germany'),
            ('DJ', 'Djibouti'),
            ('DK', 'Denmark'),
            ('DM', 'Dominica'),
            ('DO', 'Dominican Republic'),
            ('DZ', 'Algeria'),
            ('EC', 'Ecuador'),
            ('EE', 'Estonia'),
            ('EG', 'Egypt'),
            ('EH', 'Western Sahara'),
            ('ER', 'Eritrea'),
            ('ES', 'Spain'),
            ('ET', 'Ethiopia'),
            ('FI', 'Finland'),
            ('FJ', 'Fiji'),
            ('FK', 'Falkland Islands'),
            ('FM', 'Micronesia'),
            ('FO', 'Faroe Islands'),
            ('FR', 'France'),
            ('GA', 'Gabon'),
            ('GB', 'United Kingdom'),
            ('GD', 'Grenada'),
            ('GE', 'Georgia'),
            ('GF', 'French Guiana'),
            ('GG', 'Guernsey'),
            ('GH', 'Ghana'),
            ('GI', 'Gibraltar'),
            ('GL', 'Greenland'),
            ('GM', 'Gambia'),
            ('GN', 'Guinea'),
            ('GP', 'Guadeloupe'),
            ('GQ', 'Equatorial Guinea'),
            ('GR', 'Greece'),
            ('GS', 'South Georgia and the South Sandwich Islands'),
            ('GT', 'Guatemala'),
            ('GU', 'Guam'),
            ('GW', 'Guinea-Bissau'),
            ('GY', 'Guyana'),
            ('HK', 'Hong Kong'),
            ('HM', 'Heard Island and McDonald Islands'),
            ('HN', 'Honduras'),
            ('HR', 'Croatia'),
            ('HT', 'Haiti'),
            ('HU', 'Hungary'),
            ('ID', 'Indonesia'),
            ('IE', 'Ireland'),
            ('IL', 'Israel'),
            ('IM', 'Isle of Man'),
            ('IN', 'India'),
            ('IO', 'British Indian Ocean Territory'),
            ('IQ', 'Iraq'),
            ('IR', 'Iran'),
            ('IS', 'Iceland'),
            ('IT', 'Italy'),
            ('JE', 'Jersey'),
            ('JM', 'Jamaica'),
            ('JO', 'Jordan'),
            ('JP', 'Japan'),
            ('KE', 'Kenya'),
            ('KG', 'Kyrgyzstan'),
            ('KH', 'Cambodia'),
            ('KI', 'Kiribati'),
            ('KM', 'Comoros'),
            ('KN', 'Saint Kitts and Nevis'),
            ('KP', 'North Korea'),
            ('KR', 'South Korea'),
            ('KW', 'Kuwait'),
            ('KY', 'Cayman Islands'),
            ('KZ', 'Kazakhstan'),
            ('LA', 'Laos'),
            ('LB', 'Lebanon'),
            ('LC', 'Saint Lucia'),
            ('LI', 'Liechtenstein'),
            ('LK', 'Sri Lanka'),
            ('LR', 'Liberia'),
            ('LS', 'Lesotho'),
            ('LT', 'Lithuania'),
            ('LU', 'Luxembourg'),
            ('LV', 'Latvia'),
            ('LY', 'Libya'),
            ('MA', 'Morocco'),
            ('MC', 'Monaco'),
            ('MD', 'Moldova'),
            ('ME', 'Montenegro'),
            ('MF', 'Saint Martin'),
            ('MG', 'Madagascar'),
            ('MH', 'Marshall Islands'),
            ('MK', 'Macedonia'),
            ('ML', 'Mali'),
            ('MM', 'Myanmar [Burma]'),
            ('MN', 'Mongolia'),
            ('MO', 'Macao'),
            ('MP', 'Northern Mariana Islands'),
            ('MQ', 'Martinique'),
            ('MR', 'Mauritania'),
            ('MS', 'Montserrat'),
            ('MT', 'Malta'),
            ('MU', 'Mauritius'),
            ('MV', 'Maldives'),
            ('MW', 'Malawi'),
            ('MX', 'Mexico'),
            ('MY', 'Malaysia'),
            ('MZ', 'Mozambique'),
            ('NA', 'Namibia'),
            ('NC', 'New Caledonia'),
            ('NE', 'Niger'),
            ('NF', 'Norfolk Island'),
            ('NG', 'Nigeria'),
            ('NI', 'Nicaragua'),
            ('NL', 'Netherlands'),
            ('NO', 'Norway'),
            ('NP', 'Nepal'),
            ('NR', 'Nauru'),
            ('NU', 'Niue'),
            ('NZ', 'New Zealand'),
            ('OM', 'Oman'),
            ('PA', 'Panama'),
            ('PE', 'Peru'),
            ('PF', 'French Polynesia'),
            ('PG', 'Papua New Guinea'),
            ('PH', 'Philippines'),
            ('PK', 'Pakistan'),
            ('PL', 'Poland'),
            ('PM', 'Saint Pierre and Miquelon'),
            ('PN', 'Pitcairn Islands'),
            ('PR', 'Puerto Rico'),
            ('PS', 'Palestine'),
            ('PT', 'Portugal'),
            ('PW', 'Palau'),
            ('PY', 'Paraguay'),
            ('QA', 'Qatar'),
            ('RE', 'Réunion'),
            ('RO', 'Romania'),
            ('RS', 'Serbia'),
            ('RU', 'Russia'),
            ('RW', 'Rwanda'),
            ('SA', 'Saudi Arabia'),
            ('SB', 'Solomon Islands'),
            ('SC', 'Seychelles'),
            ('SD', 'Sudan'),
            ('SE', 'Sweden'),
            ('SG', 'Singapore'),
            ('SH', 'Saint Helena'),
            ('SI', 'Slovenia'),
            ('SJ', 'Svalbard and Jan Mayen'),
            ('SK', 'Slovakia'),
            ('SL', 'Sierra Leone'),
            ('SM', 'San Marino'),
            ('SN', 'Senegal'),
            ('SO', 'Somalia'),
            ('SR', 'Suriname'),
            ('SS', 'South Sudan'),
            ('ST', 'São Tomé and Príncipe'),
            ('SV', 'El Salvador'),
            ('SX', 'Sint Maarten'),
            ('SY', 'Syria'),
            ('SZ', 'Swaziland'),
            ('TC', 'Turks and Caicos Islands'),
            ('TD', 'Chad'),
            ('TF', 'French Southern Territories'),
            ('TG', 'Togo'),
            ('TH', 'Thailand'),
            ('TJ', 'Tajikistan'),
            ('TK', 'Tokelau'),
            ('TL', 'East Timor'),
            ('TM', 'Turkmenistan'),
            ('TN', 'Tunisia'),
            ('TO', 'Tonga'),
            ('TR', 'Turkey'),
            ('TT', 'Trinidad and Tobago'),
            ('TV', 'Tuvalu'),
            ('TW', 'Taiwan'),
            ('TZ', 'Tanzania'),
            ('UA', 'Ukraine'),
            ('UG', 'Uganda'),
            ('UM', 'U.S. Minor Outlying Islands'),
            ('US', 'United States'),
            ('UY', 'Uruguay'),
            ('UZ', 'Uzbekistan'),
            ('VA', 'Vatican City'),
            ('VC', 'Saint Vincent and the Grenadines'),
            ('VE', 'Venezuela'),
            ('VG', 'British Virgin Islands'),
            ('VI', 'U.S. Virgin Islands'),
            ('VN', 'Vietnam'),
            ('VU', 'Vanuatu'),
            ('WF', 'Wallis and Futuna'),
            ('WS', 'Samoa'),
            ('XK', 'Kosovo'),
            ('YE', 'Yemen'),
            ('YT', 'Mayotte'),
            ('ZA', 'South Africa'),
            ('ZM', 'Zambia'),
            ('ZW', 'Zimbabwe')
    }
    public function addPerson()
    {
        INSERT INTO `condat_v5`.`persons` (`person_id`, `first_name`, `middle_name`, `last_name`, `dob`, `sex`, `created_at`, `updated_at`) VALUES (NULL, 'Echha', NULL, 'Dangol', '1990-08-31', 'female', '2015-08-13 00:00:00', '2015-08-13 00:00:00');
    }

    public function addUser(){
        INSERT INTO `condat_v5`.`users` (`user_id`, `user_name`, `user_type`, `password`, `is_active`, `person_id`, `timezone`, `is_disabled`, `suscription_id`, `show_help_intro`, `is_super_admin`, `is_system_admin`) VALUES (NULL, 'dangolechha', 'admin', '123456', '1', '1', 'sydney', '0', '1', '1', '1', '0');
    }*/
}
